/**
 * LiveCanvas Component
 *
 * Phase 2B of Inspiration Roadmap — Thread 4 (Live Canvas)
 *
 * Main container for Live Canvas. Displays rendered artifacts,
 * manages artifact selection, and registers the canvas.render capability.
 */

import { useState, useEffect, useCallback } from 'react';
import { useCapabilities } from '../capabilities/DashboardCapabilityProvider';
import { canvasCapability, type CanvasRenderInput, type CanvasRenderResult } from '../../capabilities/canvasCapability';
import { useCanvasArtifact } from '../../hooks/useCanvasArtifact';
import { useArtifactData } from '../../hooks/useArtifactData';
import { ArtifactRenderer } from './ArtifactRenderer';
import { toArtifactId } from '@afw/shared';
import type { SessionId, ChainId, ArtifactId } from '@afw/shared';
import './LiveCanvas.css';

export interface LiveCanvasProps {
  /** Optional session filter */
  sessionId?: SessionId;
  /** Optional chain filter */
  chainId?: ChainId;
  /** Initial artifact to display */
  initialArtifactId?: ArtifactId;
}

/**
 * Live Canvas for rendering agent-generated artifacts
 */
export function LiveCanvas({ sessionId, chainId, initialArtifactId }: LiveCanvasProps) {
  const { registerCapability, unregisterCapability } = useCapabilities();
  const [selectedArtifactId, setSelectedArtifactId] = useState<ArtifactId | null>(
    initialArtifactId || null
  );

  // Fetch artifact list
  const { artifacts, loading: listLoading, error: listError } = useArtifactData({
    sessionId,
    chainId,
    autoFetch: true,
  });

  // Fetch selected artifact details
  const {
    artifact: selectedArtifact,
    loading: artifactLoading,
    error: artifactError,
  } = useCanvasArtifact({
    artifactId: selectedArtifactId!,
    autoFetch: !!selectedArtifactId,
  });

  // Capability handler: render an artifact
  const handleRenderArtifact = useCallback(
    async (inputs: Record<string, unknown>): Promise<CanvasRenderResult> => {
      const { artifactId, focus } = inputs as unknown as CanvasRenderInput;

      if (!artifactId) {
        throw new Error('artifactId is required');
      }

      const id = toArtifactId(artifactId);
      setSelectedArtifactId(id);

      // If focus is requested, bring the canvas into view
      if (focus) {
        // This could scroll to the canvas or switch tabs
        // For now, just a placeholder
        console.log('[LiveCanvas] Bringing canvas into focus');
      }

      return {
        success: true,
        artifactId: id,
        renderedAt: new Date().toISOString(),
      };
    },
    []
  );

  // Register capability on mount
  useEffect(() => {
    registerCapability(canvasCapability, handleRenderArtifact);

    return () => {
      unregisterCapability(canvasCapability.id);
    };
  }, [registerCapability, unregisterCapability, handleRenderArtifact]);

  // Auto-select first artifact if none selected
  useEffect(() => {
    if (!selectedArtifactId && artifacts.length > 0) {
      const activeArtifacts = artifacts.filter(a => a.status === 'active');
      if (activeArtifacts.length > 0) {
        setSelectedArtifactId(activeArtifacts[0].id);
      } else {
        setSelectedArtifactId(artifacts[0].id);
      }
    }
  }, [artifacts, selectedArtifactId]);

  const handleArtifactSelect = (artifactId: ArtifactId) => {
    setSelectedArtifactId(artifactId);
  };

  const handleRenderError = (error: Error) => {
    console.error('[LiveCanvas] Render error:', error);
  };

  // Show loading state
  if (listLoading && artifacts.length === 0) {
    return (
      <div className="live-canvas">
        <div className="live-canvas__loading">
          <div className="live-canvas__spinner" />
          <div className="live-canvas__loading-text">Loading artifacts...</div>
        </div>
      </div>
    );
  }

  // Show error state
  if (listError && artifacts.length === 0) {
    return (
      <div className="live-canvas">
        <div className="live-canvas__error">
          <div className="live-canvas__error-icon">⚠️</div>
          <div className="live-canvas__error-message">Failed to load artifacts</div>
          <div className="live-canvas__error-details">{listError}</div>
        </div>
      </div>
    );
  }

  // Show empty state
  if (artifacts.length === 0) {
    return (
      <div className="live-canvas">
        <div className="live-canvas__empty">
          <div className="live-canvas__empty-icon">🎨</div>
          <div className="live-canvas__empty-title">No artifacts yet</div>
          <div className="live-canvas__empty-message">
            Artifacts generated by agents will appear here
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="live-canvas">
      <div className="live-canvas__sidebar">
        <div className="live-canvas__sidebar-header">
          <h3 className="live-canvas__sidebar-title">Artifacts</h3>
          <div className="live-canvas__sidebar-count">{artifacts.length}</div>
        </div>
        <div className="live-canvas__artifact-list">
          {artifacts.map(artifact => (
            <button
              key={artifact.id}
              className={`live-canvas__artifact-item ${
                selectedArtifactId === artifact.id ? 'live-canvas__artifact-item--active' : ''
              }`}
              onClick={() => handleArtifactSelect(artifact.id)}
            >
              <div className="live-canvas__artifact-type">{artifact.type}</div>
              <div className="live-canvas__artifact-title">
                {artifact.title || `Artifact ${artifact.id.slice(0, 8)}`}
              </div>
              <div className="live-canvas__artifact-meta">
                {artifact.status === 'archived' && (
                  <span className="live-canvas__artifact-badge live-canvas__artifact-badge--archived">
                    Archived
                  </span>
                )}
                {artifact.status === 'error' && (
                  <span className="live-canvas__artifact-badge live-canvas__artifact-badge--error">
                    Error
                  </span>
                )}
              </div>
            </button>
          ))}
        </div>
      </div>

      <div className="live-canvas__viewport">
        {selectedArtifact ? (
          <ArtifactRenderer artifact={selectedArtifact} onError={handleRenderError} />
        ) : artifactLoading ? (
          <div className="live-canvas__loading">
            <div className="live-canvas__spinner" />
            <div className="live-canvas__loading-text">Loading artifact...</div>
          </div>
        ) : artifactError ? (
          <div className="live-canvas__error">
            <div className="live-canvas__error-icon">⚠️</div>
            <div className="live-canvas__error-message">Failed to load artifact</div>
            <div className="live-canvas__error-details">{artifactError}</div>
          </div>
        ) : (
          <div className="live-canvas__empty">
            <div className="live-canvas__empty-icon">🎨</div>
            <div className="live-canvas__empty-title">Select an artifact</div>
            <div className="live-canvas__empty-message">
              Choose an artifact from the sidebar to view it here
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
