/**
 * Agent Integrity Service
 *
 * Computes and verifies SHA-256 checksums of all agent.md files to detect
 * unauthorized modifications mid-session.
 *
 * Generated by health-protocol Phase 5d (Eyes agent, qwen3:14b)
 * Addresses learning L024 (ESCALATED): Zero input protection for agent.md files.
 *
 * @see .claude/actionflows/actions/{action}/agent.md
 * @see .claude/actionflows/LEARNINGS.md L024
 */

import { createHash } from 'crypto';
import { readFile, readdir } from 'fs/promises';
import { join, resolve } from 'path';
import { EventEmitter } from 'events';

export interface AgentChecksum {
  /** Relative path from project root */
  path: string;
  /** SHA-256 hex digest */
  hash: string;
}

export interface IntegrityViolation {
  path: string;
  expectedHash: string;
  actualHash: string;
  detectedAt: string;
}

export class AgentIntegrityService extends EventEmitter {
  private checksums: Map<string, string> = new Map();
  private baseDir: string;

  constructor(baseDir?: string) {
    super();
    this.baseDir = baseDir ?? resolve('.claude', 'actionflows', 'actions');
  }

  /**
   * Scan all agent.md files and compute initial checksums
   */
  async initialize(): Promise<void> {
    this.checksums.clear();

    try {
      const entries = await readdir(this.baseDir, { withFileTypes: true });
      const dirs = entries.filter(e => e.isDirectory());

      for (const dir of dirs) {
        const agentMdPath = join(this.baseDir, dir.name, 'agent.md');
        try {
          const content = await readFile(agentMdPath, 'utf-8');
          const hash = this.computeHash(content);
          this.checksums.set(agentMdPath, hash);
        } catch {
          // agent.md doesn't exist in this directory — skip
        }
      }

      console.log(`[AgentIntegrity] Initialized: ${this.checksums.size} agent.md files checksummed`);
    } catch (error) {
      console.error('[AgentIntegrity] Failed to initialize:', error);
    }
  }

  /**
   * Verify an agent.md file hasn't been modified since initialization
   */
  async verify(actionName: string): Promise<{ valid: boolean; violation?: IntegrityViolation }> {
    const filePath = join(this.baseDir, actionName, 'agent.md');
    const expectedHash = this.checksums.get(filePath);

    if (!expectedHash) {
      console.warn(`[AgentIntegrity] No baseline checksum for: ${filePath}`);
      return { valid: true }; // No baseline = can't detect drift
    }

    try {
      const content = await readFile(filePath, 'utf-8');
      const actualHash = this.computeHash(content);

      if (actualHash !== expectedHash) {
        const violation: IntegrityViolation = {
          path: filePath,
          expectedHash,
          actualHash,
          detectedAt: new Date().toISOString(),
        };

        console.warn(`[AgentIntegrity] VIOLATION: ${filePath} modified mid-session!`);
        this.emit('integrity:violation', violation);
        return { valid: false, violation };
      }

      return { valid: true };
    } catch (error) {
      console.error(`[AgentIntegrity] Failed to verify ${filePath}:`, error);
      return { valid: true }; // Read error = don't block spawning
    }
  }

  /**
   * Refresh checksums after approved modifications (e.g., evolve command)
   */
  async refreshChecksums(): Promise<void> {
    await this.initialize();
    console.log('[AgentIntegrity] Checksums refreshed');
  }

  /**
   * Get all current checksums for inspection
   */
  getChecksums(): AgentChecksum[] {
    return Array.from(this.checksums.entries()).map(([path, hash]) => ({ path, hash }));
  }

  private computeHash(content: string): string {
    return createHash('sha256').update(content).digest('hex');
  }
}

// ============================================================================
// Singleton Instance
// ============================================================================

let instance: AgentIntegrityService | null = null;

/**
 * Initialize the AgentIntegrityService singleton
 * Call once during backend startup
 */
export async function initAgentIntegrity(baseDir?: string): Promise<AgentIntegrityService> {
  if (!instance) {
    instance = new AgentIntegrityService(baseDir);
    await instance.initialize();
  }
  return instance;
}

/**
 * Get the AgentIntegrityService singleton
 * Throws if not initialized
 */
export function getAgentIntegrity(): AgentIntegrityService {
  if (!instance) {
    throw new Error('AgentIntegrityService not initialized. Call initAgentIntegrity() first.');
  }
  return instance;
}
